import type { Place } from '@/model/types';

// OFFLINE BOSTON PLACE CATALOG — POWERS THE LOCAL PROVIDER WHEN NO MAPBOX
// TOKEN IS CONFIGURED, AND KEEPS THE DEMO/TESTS DETERMINISTIC AND OFFLINE
// (PLAN §1 PRINCIPLE 5). HOURS ARE PLAUSIBLE DEMO DATA, NOT LIVE TRUTH.

// SHORTHAND: SAME WINDOW EVERY DAY, WITH OPTIONAL CLOSED WEEKDAYS (0=SUN).
function daily(open_min: number, close_min: number, closed_days: number[] = []) {
  return {
    weekly: Array.from({ length: 7 }, (_, d) =>
      closed_days.includes(d) ? [] : [{ open_min, close_min }],
    ),
  };
}

const H = 60;

export const local_catalog: Place[] = [
  {
    place_id: 'loc_mfa',
    name: 'Museum of Fine Arts',
    address: '465 Huntington Ave',
    coords: { lat: 42.3394, lng: -71.0942 },
    poi_category: 'museum',
    hours: daily(10 * H, 17 * H, [2]),
  },
  {
    place_id: 'loc_gardner',
    name: 'Isabella Stewart Gardner Museum',
    address: '25 Evans Way',
    coords: { lat: 42.3382, lng: -71.0991 },
    poi_category: 'museum',
    hours: daily(11 * H, 17 * H, [2]),
  },
  {
    place_id: 'loc_harvard_nat',
    name: 'Harvard Museum of Natural History',
    address: '26 Oxford St, Cambridge',
    coords: { lat: 42.3784, lng: -71.1155 },
    poi_category: 'museum',
    hours: daily(9 * H, 17 * H),
  },
  {
    place_id: 'loc_tea_party',
    name: 'Boston Tea Party Ships & Museum',
    address: 'Congress St Bridge',
    coords: { lat: 42.3522, lng: -71.0513 },
    poi_category: 'museum',
    hours: daily(10 * H, 17 * H),
  },
  {
    place_id: 'loc_ica',
    name: 'Institute of Contemporary Art',
    address: '25 Harbor Shore Dr',
    coords: { lat: 42.3529, lng: -71.0429 },
    poi_category: 'museum',
    hours: daily(10 * H, 17 * H, [1]),
  },
  {
    place_id: 'loc_paul_revere',
    name: 'Paul Revere House',
    address: '19 N Square',
    coords: { lat: 42.3637, lng: -71.0537 },
    poi_category: 'landmark',
    hours: daily(9 * H + 30, 17 * H + 15),
  },
  {
    place_id: 'loc_old_north',
    name: 'Old North Church',
    address: '193 Salem St',
    coords: { lat: 42.3663, lng: -71.0544 },
    poi_category: 'landmark',
    hours: daily(10 * H, 17 * H),
  },
  {
    place_id: 'loc_bunker_hill',
    name: 'Bunker Hill Monument',
    address: 'Monument Sq, Charlestown',
    coords: { lat: 42.3764, lng: -71.0608 },
    poi_category: 'landmark',
    hours: daily(10 * H, 16 * H + 30),
  },
  {
    place_id: 'loc_faneuil',
    name: 'Faneuil Hall Marketplace',
    address: '4 S Market St',
    coords: { lat: 42.36, lng: -71.0545 },
    poi_category: 'market',
    hours: daily(10 * H, 21 * H),
  },
  {
    place_id: 'loc_quincy',
    name: 'Quincy Market',
    address: '206 S Market St',
    coords: { lat: 42.3599, lng: -71.0537 },
    poi_category: 'market',
    hours: daily(10 * H, 21 * H),
  },
  {
    place_id: 'loc_time_out',
    name: 'Time Out Market Boston',
    address: '401 Park Dr',
    coords: { lat: 42.3441, lng: -71.1017 },
    poi_category: 'market',
    hours: daily(11 * H, 22 * H),
  },
  {
    place_id: 'loc_public_garden',
    name: 'Boston Public Garden',
    address: '4 Charles St',
    coords: { lat: 42.3541, lng: -71.0704 },
    poi_category: 'park',
    hours: daily(6 * H, 23 * H),
  },
  {
    place_id: 'loc_common',
    name: 'Boston Common',
    address: '139 Tremont St',
    coords: { lat: 42.3551, lng: -71.0657 },
    poi_category: 'park',
    hours: daily(6 * H, 23 * H),
  },
  {
    place_id: 'loc_esplanade',
    name: 'Charles River Esplanade',
    address: 'Storrow Dr',
    coords: { lat: 42.356, lng: -71.0805 },
    poi_category: 'park',
    hours: daily(0, 24 * H),
  },
  {
    place_id: 'loc_fenway',
    name: 'Fenway Park',
    address: '4 Jersey St',
    coords: { lat: 42.3467, lng: -71.0972 },
    poi_category: 'stadium',
    hours: daily(9 * H, 17 * H),
  },
  {
    place_id: 'loc_aquarium',
    name: 'New England Aquarium',
    address: '1 Central Wharf',
    coords: { lat: 42.3592, lng: -71.0499 },
    poi_category: 'aquarium',
    hours: daily(9 * H, 18 * H),
  },
  {
    place_id: 'loc_skywalk',
    name: 'View Boston Observatory',
    address: '800 Boylston St',
    coords: { lat: 42.3473, lng: -71.0823 },
    poi_category: 'observatory',
    hours: daily(10 * H, 22 * H),
  },
  {
    place_id: 'loc_freedom_trail',
    name: 'Freedom Trail',
    address: 'Boston Common to Bunker Hill',
    coords: { lat: 42.3557, lng: -71.0637 },
    poi_category: 'trail',
    hours: daily(0, 24 * H),
  },
  {
    place_id: 'loc_harvard_yard',
    name: 'Harvard Yard',
    address: 'Cambridge, MA',
    coords: { lat: 42.3744, lng: -71.1169 },
    poi_category: 'landmark',
    hours: daily(0, 24 * H),
  },
  {
    place_id: 'loc_newbury',
    name: 'Newbury Street',
    address: 'Back Bay',
    coords: { lat: 42.3496, lng: -71.0825 },
    poi_category: 'neighborhood',
    hours: daily(0, 24 * H),
  },
  {
    place_id: 'loc_beacon_hill',
    name: 'Beacon Hill & Acorn Street',
    address: 'Beacon Hill',
    coords: { lat: 42.3588, lng: -71.0707 },
    poi_category: 'neighborhood',
    hours: daily(0, 24 * H),
  },
  {
    place_id: 'loc_harborwalk',
    name: 'Harborwalk',
    address: 'Seaport',
    coords: { lat: 42.3541, lng: -71.0466 },
    poi_category: 'trail',
    hours: daily(0, 24 * H),
  },
  {
    place_id: 'loc_tatte',
    name: 'Tatte Bakery & Cafe',
    address: '70 Charles St',
    coords: { lat: 42.3581, lng: -71.0703 },
    poi_category: 'cafe',
    hours: daily(7 * H, 19 * H),
  },
  {
    place_id: 'loc_thinking_cup',
    name: 'Thinking Cup',
    address: '165 Tremont St',
    coords: { lat: 42.3529, lng: -71.0646 },
    poi_category: 'cafe',
    hours: daily(7 * H, 20 * H),
  },
  {
    place_id: 'loc_mikes',
    name: "Mike's Pastry",
    address: '300 Hanover St',
    coords: { lat: 42.3647, lng: -71.0542 },
    poi_category: 'bakery',
    hours: daily(8 * H, 22 * H),
  },
  {
    place_id: 'loc_modern',
    name: 'Modern Pastry',
    address: '257 Hanover St',
    coords: { lat: 42.3634, lng: -71.0549 },
    poi_category: 'bakery',
    hours: daily(8 * H, 21 * H),
  },
  {
    place_id: 'loc_neptune',
    name: 'Neptune Oyster',
    address: '63 Salem St',
    coords: { lat: 42.3632, lng: -71.056 },
    poi_category: 'restaurant',
    hours: daily(11 * H + 30, 21 * H + 30),
  },
  {
    place_id: 'loc_union_oyster',
    name: 'Union Oyster House',
    address: '41 Union St',
    coords: { lat: 42.3613, lng: -71.057 },
    poi_category: 'restaurant',
    hours: daily(11 * H, 21 * H),
  },
  {
    place_id: 'loc_saltie',
    name: 'Saltie Girl',
    address: '281 Dartmouth St',
    coords: { lat: 42.3506, lng: -71.0788 },
    poi_category: 'restaurant',
    hours: daily(11 * H, 22 * H),
  },
  {
    place_id: 'loc_bartleys',
    name: "Mr. Bartley's Burger Cottage",
    address: '1246 Massachusetts Ave, Cambridge',
    coords: { lat: 42.3721, lng: -71.1174 },
    poi_category: 'restaurant',
    hours: daily(11 * H, 21 * H, [0]),
  },
];
