import type { PlaceHours, Trip } from '@/model/types';

// SAME-WINDOW-DAILY SHORTHAND FOR SEED PLACES (0=SUN IN closed_days).
function daily(open_min: number, close_min: number, closed_days: number[] = []): PlaceHours {
  return {
    weekly: Array.from({ length: 7 }, (_, d) =>
      closed_days.includes(d) ? [] : [{ open_min, close_min }],
    ),
  };
}

// HARDCODED BOSTON TRIP (PLAN.MD §5 REFERENCE FLOW) — NOW A TEST/DEMO FIXTURE
// ONLY, LOADED WHEN THE APP IS EXPORTED WITH EXPO_PUBLIC_SEED_DEMO=1 (THE
// HEADLESS SUITE DEPENDS ON IT). REAL SESSIONS START EMPTY.
export const boston_trip: Trip = {
  id: 'trip_boston',
  title: 'Boston',
  destination: 'Boston, MA',
  anchor: { lat: 42.3601, lng: -71.0589 },
  start_date: '2026-08-12',
  end_date: '2026-08-16',
  travelers: 2,
  preferences: { pace: 'balanced', budget_tier: 2, interests: ['food', 'history', 'walkable'] },
  idea_shelf: [
    {
      id: 'shelf_1',
      title: 'Fenway Park tour',
      block_type: 'activity',
      place: { name: 'Fenway Park', address: '4 Jersey St' },
      typical_duration_min: 90,
    },
    {
      id: 'shelf_2',
      title: 'Tatte Bakery',
      block_type: 'meal',
      place: {
        name: 'Tatte Bakery & Cafe',
        address: 'Charles St',
        coords: { lat: 42.3581, lng: -71.0703 },
        poi_category: 'cafe',
        hours: daily(420, 1140),
      },
      typical_duration_min: 45,
    },
    {
      id: 'shelf_3',
      title: 'Boston Tea Party Museum',
      block_type: 'activity',
      place: { name: 'Boston Tea Party Ships & Museum', address: 'Congress St Bridge' },
      typical_duration_min: 75,
    },
  ],
  days: [
    {
      id: 'day_1',
      date: '2026-08-12',
      theme_label: 'Arrival & Back Bay',
      blocks: [
        {
          id: 'b_101',
          block_type: 'flight',
          title: 'DL 1204 · JFK → BOS',
          start_time: 605,
          end_time: 700,
          source: 'manual',
          is_locked: true,
          booking: { confirmation_number: 'GKX4LM', provider: 'Delta', status: 'booked' },
          meta: {
            chip: { label: 'Booked', kind: 'anchor' },
            transit_to_next: { mode: 'drive', duration_min: 24, distance_mi: 4.1 },
          },
        },
        {
          id: 'b_102',
          block_type: 'lodging',
          title: 'Check in · The Revere Hotel',
          start_time: 900,
          end_time: 930,
          source: 'manual',
          is_locked: true,
          place: {
            name: 'The Revere Hotel',
            address: '200 Stuart St',
            coords: { lat: 42.3512, lng: -71.0672 },
            poi_category: 'lodging',
          },
          booking: { confirmation_number: 'RV48219', provider: 'Revere', status: 'booked' },
          meta: { chip: { label: 'Booked', kind: 'anchor' } },
        },
        {
          id: 'b_103',
          block_type: 'activity',
          title: 'Newbury Street stroll',
          start_time: 960,
          end_time: 1050,
          source: 'manual',
          is_locked: false,
          place: {
            name: 'Newbury Street',
            coords: { lat: 42.3496, lng: -71.0825 },
            poi_category: 'neighborhood',
          },
        },
        {
          id: 'b_104',
          block_type: 'meal',
          title: 'Dinner at Saltie Girl',
          start_time: 1140,
          end_time: 1230,
          source: 'manual',
          is_locked: false,
          place: {
            name: 'Saltie Girl',
            address: '281 Dartmouth St',
            coords: { lat: 42.3506, lng: -71.0788 },
            poi_category: 'restaurant',
            hours: daily(660, 1320),
          },
          booking: { status: 'needs_booking' },
          meta: { chip: { label: 'Book ahead', kind: 'meal' } },
        },
      ],
    },
    {
      id: 'day_2',
      date: '2026-08-13',
      theme_label: 'North End & Harbor',
      blocks: [
        {
          id: 'b_201',
          block_type: 'meal',
          title: 'Coffee at Thinking Cup',
          start_time: 510,
          end_time: 540,
          source: 'manual',
          is_locked: false,
          place: {
            name: 'Thinking Cup',
            hours_label: 'Open now',
            coords: { lat: 42.3529, lng: -71.0646 },
            poi_category: 'cafe',
          },
          meta: { chip: { label: 'Open now', kind: 'anchor' } },
        },
        {
          id: 'b_202',
          block_type: 'activity',
          title: 'Freedom Trail · south half',
          start_time: 570,
          end_time: 720,
          source: 'manual',
          is_locked: false,
          place: {
            name: 'Freedom Trail',
            coords: { lat: 42.3576, lng: -71.0603 },
            poi_category: 'trail',
          },
        },
        {
          id: 'b_203',
          block_type: 'meal',
          title: 'Lunch in the North End',
          start_time: 735,
          end_time: 810,
          source: 'manual',
          is_locked: false,
          place: {
            name: 'North End',
            coords: { lat: 42.3633, lng: -71.0552 },
            poi_category: 'neighborhood',
          },
        },
        {
          id: 'b_204',
          block_type: 'activity',
          title: 'Paul Revere House',
          start_time: 820,
          end_time: 870,
          source: 'manual',
          is_locked: false,
          place: {
            name: 'Paul Revere House',
            coords: { lat: 42.3637, lng: -71.0537 },
            poi_category: 'landmark',
            hours: daily(570, 1035),
          },
        },
        {
          id: 'b_205',
          block_type: 'activity',
          title: 'Harborwalk to Long Wharf',
          start_time: 900,
          end_time: 960,
          source: 'manual',
          is_locked: false,
          place: {
            name: 'Long Wharf',
            coords: { lat: 42.36, lng: -71.05 },
            poi_category: 'trail',
          },
        },
        {
          id: 'b_206',
          block_type: 'meal',
          title: 'Dinner with Sarah',
          start_time: 1140,
          end_time: 1260,
          source: 'manual',
          is_locked: false,
          notes: 'She books the spot — just show up.',
        },
      ],
    },
    {
      id: 'day_3',
      date: '2026-08-14',
      theme_label: 'Harvard & Cambridge',
      blocks: [
        {
          id: 'b_301',
          block_type: 'activity',
          title: 'Harvard Yard walking tour',
          start_time: 600,
          end_time: 690,
          source: 'manual',
          is_locked: false,
          place: {
            name: 'Harvard Yard',
            coords: { lat: 42.3744, lng: -71.1169 },
            poi_category: 'landmark',
          },
        },
        {
          id: 'b_302',
          block_type: 'meal',
          title: "Lunch at Mr. Bartley's",
          start_time: 720,
          end_time: 780,
          source: 'manual',
          is_locked: false,
          place: {
            name: "Mr. Bartley's Burger Cottage",
            hours_label: 'Open until 9 PM',
            coords: { lat: 42.3721, lng: -71.1174 },
            poi_category: 'restaurant',
          },
        },
        {
          id: 'b_303',
          block_type: 'activity',
          title: 'Harvard Museum of Natural History',
          start_time: 795,
          end_time: 900,
          source: 'manual',
          is_locked: false,
          place: {
            name: 'Harvard Museum of Natural History',
            coords: { lat: 42.3784, lng: -71.1155 },
            poi_category: 'museum',
            hours: daily(540, 1020),
          },
          meta: {
            chip: { label: 'Closes 5 PM', kind: 'neutral' },
            transit_to_next: { mode: 'transit', duration_min: 26 },
          },
        },
        {
          id: 'b_304',
          block_type: 'buffer',
          title: 'Back to hotel · rest',
          start_time: 940,
          end_time: 1020,
          source: 'manual',
          is_locked: false,
        },
      ],
    },
    {
      id: 'day_4',
      date: '2026-08-15',
      theme_label: 'Fenway & MFA',
      blocks: [
        {
          id: 'b_401',
          block_type: 'activity',
          title: 'Museum of Fine Arts',
          start_time: 600,
          end_time: 720,
          source: 'manual',
          is_locked: false,
          place: {
            name: 'Museum of Fine Arts',
            coords: { lat: 42.3394, lng: -71.0942 },
            poi_category: 'museum',
            hours: daily(600, 1020, [2]),
          },
          meta: { chip: { label: 'Open 10 – 5', kind: 'anchor' } },
        },
        {
          id: 'b_402',
          block_type: 'meal',
          title: 'Lunch at Time Out Market',
          start_time: 750,
          end_time: 810,
          source: 'manual',
          is_locked: false,
          place: {
            name: 'Time Out Market Boston',
            coords: { lat: 42.3441, lng: -71.1017 },
            poi_category: 'market',
          },
        },
        {
          id: 'b_403',
          block_type: 'activity',
          title: 'Fenway Park tour',
          start_time: 840,
          end_time: 930,
          source: 'manual',
          is_locked: false,
          place: {
            name: 'Fenway Park',
            coords: { lat: 42.3467, lng: -71.0972 },
            poi_category: 'stadium',
          },
          booking: { status: 'needs_booking' },
          meta: { chip: { label: 'Book ahead', kind: 'meal' } },
        },
        {
          id: 'b_404',
          block_type: 'meal',
          title: 'Dinner in Back Bay',
          start_time: 1140,
          end_time: 1230,
          source: 'manual',
          is_locked: false,
        },
      ],
    },
    {
      id: 'day_5',
      date: '2026-08-16',
      theme_label: 'Harbor & home',
      blocks: [
        {
          id: 'b_501',
          block_type: 'lodging',
          title: 'Check out · The Revere Hotel',
          start_time: 600,
          end_time: 630,
          source: 'manual',
          is_locked: true,
          place: {
            name: 'The Revere Hotel',
            coords: { lat: 42.3512, lng: -71.0672 },
            poi_category: 'lodging',
          },
          booking: { confirmation_number: 'RV48219', provider: 'Revere', status: 'booked' },
          meta: { chip: { label: 'Booked', kind: 'anchor' } },
        },
        {
          id: 'b_502',
          block_type: 'activity',
          title: 'Boston Public Garden',
          start_time: 660,
          end_time: 720,
          source: 'manual',
          is_locked: false,
          place: {
            name: 'Boston Public Garden',
            coords: { lat: 42.3541, lng: -71.0704 },
            poi_category: 'park',
          },
          // AIRPORT LEG STAYS HAND-SET — THE FLIGHT BLOCK CARRIES NO COORDS.
          meta: { transit_to_next: { mode: 'drive', duration_min: 25, distance_mi: 4.3 } },
        },
        {
          id: 'b_503',
          block_type: 'flight',
          title: 'DL 2210 · BOS → JFK',
          start_time: 940,
          end_time: 1025,
          source: 'manual',
          is_locked: true,
          booking: { confirmation_number: 'GKX4LM', provider: 'Delta', status: 'booked' },
          meta: { chip: { label: 'Booked', kind: 'anchor' } },
        },
      ],
    },
  ],
};
