// SHARED GEOMETRY FOR THE COMPRESSED-TIME TIMELINE: BLOCKS ARE
// DURATION-PROPORTIONAL (RESIZING AN EVENT GROWS THE TIMELINE), BUT EMPTY TIME
// COLLAPSES INTO A COMPACT GAP BAND SO SPARSE DAYS STAY SHORT.

export const PX_PER_MIN = 1.2; // BLOCK SCALE: 1 HOUR OF EVENT = 72PX
// EVEN OUTER PADDING: THE RAIL SITS EDGE_PAD FROM THE LEFT EDGE AND CARDS END
// EDGE_PAD FROM THE RIGHT EDGE.
export const EDGE_PAD = 12;
export const RAIL_W = 34; // "12:00" ON ONE LINE; AM/PM STACKS BELOW
export const MIN_BLOCK_MIN = 30;
// ROOMIER GAP BETWEEN THE RAIL TIMES AND THE CARDS.
export const CARD_LEFT = EDGE_PAD + RAIL_W + 12;
export const CARD_RIGHT = EDGE_PAD;
export const CANVAS_PAD = 10;
export const DAY_MIN = 1440;

// GAP BANDS: PROPORTIONAL WHEN SHORT, CLAMPED WHEN THE AFTERNOON IS EMPTY.
export const GAP_MIN_PX = 22;
export const GAP_MAX_PX = 64;
export const BLOCK_SPACER_PX = 4; // BACK-TO-BACK BLOCKS STILL GET A SEAM
// A CONFLICTED BLOCK RENDERS AT LEAST THIS TALL — ROOM FOR THE TITLE, TIME
// LABEL, AND THE CONFLICT BANNER WITH ITS ICON BADGE AND FIX PILL.
export const CONFLICT_MIN_PX = 96;

export function min_to_px(min: number): number {
  return min * PX_PER_MIN;
}
